### ISSUE TITLE
Add CSS classes to the created element in the modal?

### ISSUE THREAD

**Issue by george-silva** [awkward/backbone.modal#79]
I want to have variable width modals. I can configure them in the view, using the className property. But that is applied to the bbm-wrapper element.

Is it possible to configure a class to be dinamically in the div that comes with bbm-modal class?

**Comment by zeakd** [comment]
The problem is, setting className on BackBone.Modal is adding them to '.bbm-wrapper', not .bbm-modal. 
I solved it just adding '.bbm-modal-{{size}}' on modalEl
``` js
onRender: function () {
    this.modalEl.addClass('bbm-modal-large')
}
```
``` css
.bbm-modal {
  max-width: none;
}
.bbm-modal-large {
  width : 980px;
}
```
